# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpTlC4HgRHHTPK6z8FXogCqncTtmu6b-
"""



"""Criando os chunkings

"""

def sentimento(nota):
    if nota >= 4:
        return "positivo"
    elif nota == 3:
        return "neutro"
    else:
        return "negativo"

documents = []

for item in data:
    doc = {
        "text": item.get("content", ""),
        "produto": extrair_nome_produto(item.get("product_url", "")),
        "nota": item.get("rating", 0),
        "sentimento": sentimento(item.get("rating", 0))
    }

    if doc["text"]:
        documents.append(doc)

print("Total de documentos:", len(documents))
print(documents[0])

"""Embeddings"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

texts = [doc["text"] for doc in documents]

embeddings = model.encode(texts, show_progress_bar=True)

print("Dimensão do vetor:", len(embeddings[0]))

from qdrant_client import QdrantClient

client = QdrantClient(":memory:")

client.recreate_collection(
    collection_name="reviews",
    vectors_config={
        "size": len(embeddings[0]),
        "distance": "Cosine"
    }
)

from qdrant_client.models import PointStruct

points = []

for i, doc in enumerate(documents):
    points.append(PointStruct(
        id=i,
        vector=embeddings[i].tolist(),
        payload=doc
    ))

client.upsert(
    collection_name="reviews",
    points=points
)

query = "shampoo bom para caspa"

query_vector = model.encode(query).tolist()

results = client.query_points(
    collection_name="reviews",
    query=query_vector,
    limit=5
)

for r in results.points:
    print(r.payload)

"""Simular RAG"""

def buscar_contexto(pergunta, top_k=5):
    query_vector = model.encode(pergunta).tolist()

    results = client.query_points(
        collection_name="reviews",
        query=query_vector,
        limit=top_k
    )

    contextos = []

    for r in results.points:
        payload = r.payload

        if payload["sentimento"] == "positivo":
            contexto = f"""
Produto:{payload['produto']}
Avaliação: {payload['text']}
Nota: {payload['nota']}
"""
            contextos.append(contexto)

    return contextos


def extrair_nome_produto(url):
    return url.split("/")[-1].replace("-", " ")


from groq import Groq

client_groq = Groq(api_key=os.environ["GROQ_API_KEY"])

def gerar_resposta_llm(pergunta):
    contextos = buscar_contexto(pergunta, top_k=5)

    contexto_texto = "\n".join(contextos)

    prompt = f"""
Você é um assistente especialista em recomendar produtos de beleza.

Use apenas as avaliações abaixo para responder.

Pergunta:
{pergunta}

Avaliações:
{contexto_texto}

Instruções:
- Sugira produtos com base nas avaliações
- Priorize avaliações positivas
- Seja claro e objetivo
- Não invente informações
"""

    resposta = client_groq.chat.completions.create(
      model="llama-3.1-8b-instant",
      messages=[
          {"role": "user", "content": prompt}
      ],
      temperature=0.3
  )

    return resposta.choices[0].message.content

print(gerar_resposta_llm("qual um bom shampoo anticaspa?"))